# Generated by Django 3.2 on 2023-03-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_favoritesensor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteSensor',
        ),
    ]
