# Generated by Django 3.2 on 2023-03-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_alter_sensordata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-date_updated',)},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('-date_updated',)},
        ),
    ]
