# Generated by Django 3.2 on 2023-03-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0005_auto_20230303_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_leap_year', models.BooleanField(blank=True, default=False)),
                ('is_week_day', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Date info',
            },
        ),
        migrations.CreateModel(
            name='FactSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='hour', max_length=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_data', to='data_warehouse.dateinfo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_data', to='iot.sensor')),
            ],
            options={
                'verbose_name_plural': 'Sensor data (warehouse)',
            },
        ),
    ]
