# Generated by Django 3.2 on 2023-03-11 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
